### ISSUE TITLE
The Epic Road to Fairness

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#47]
The plan for both short and long term future development of this project will be discussed here. This is just a road map to have a 
bird's-eye view on the project and each task should be defined in details in another issue page if needed. In case a separate issue page is created for a task, it should be linked here by the number of created issue.

0- Datasets ( existing and new potential datasets and their related tasks)
- [ ]  Inferring the gender labels for DBLP dataset #36 
- [ ]  Collect and process GitHub dataset
- [ ] [ TREC. W3C Experts](https://github.com/MilkaLichtblau/DELTR-Experiments/tree/master/data/TREC) used in [Reducing Disparate Exposure in Ranking: A Learning To Rank Approach](https://arxiv.org/abs/1805.08716)
- [ ] [ Semantic Scholar Open Research Corpus](https://www.semanticscholar.org/product/api) used in [Interventions for ranking in the presence of implicit bias](https://dl.acm.org/doi/abs/10.1145/3351095.3372858)

1- Ranking Methods

- [ ] Double cutoff method for OpeNTF and [Fairness-Aware Ranking in Search & Recommendation Systems with Application to LinkedIn Talent Search](https://dl.acm.org/doi/10.1145/3292500.3330691) 
- [ ] Add [FA*IR: A Fair Top-k Ranking Algorithm](https://dl.acm.org/doi/10.1145/3132847.3132938) to the pipeline

2- Refactor and Debug

- [ ] Change popularity label files from csv to binary
- [ ] f'{new_output}.{algorithm}.{k_max}.rerank.csv' => binary
- [ ] Separate the layers of the pipeline (dal, rerank, eval layers)
- [ ] Cutoff for popular/nonpopular based on distribution diagram
- [ ] Add another fairness metric (from  normalized discounted difference (rND), ratio (rRD), and KL-divergence (rKL) proposed in [Measuring Fairness in Ranked Outputs](https://dl.acm.org/doi/10.1145/3085504.3085526))
- [ ] 2d scatter diagram for fairness vs utility

3- Reading 
- [ ] Explore papers for other state-of-the-art score-based ranking and learning to rank methods
- [ ] Practical Fairness Achieving Fair and Secure Data Models Book

**Comment by hosseinfani** [comment]
@Hamedloghmani 
Any progress with any of these tasks?

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Yes, these are the stuff that are going to be finished and reported by the end of the day:

- Summary of [FA*IR: A Fair Top-k Ranking Algorithm](https://dl.acm.org/doi/10.1145/3132847.3132938) will be finished and uploaded
- Our labeling procedure for DBLP has 3 phases :   1) Analysis and automatically extract unique names from DBLB 2) API purchase and label unique names 3)Patch back the names to the dataset ( log is in #36 )
Phase 1 has finished last night we are on phase 2, I will purchase the API today.
- The write-up of the summary of deterministic reranking algorithms will be finished and uploaded
- Analysis and unique name results for the whole DBLP dataset is available in Teams -> Adila -> DBLP Labeling files
- Github crawler is on 800,000 record. About 200,000 to go

These are next in the queue:

1. Adding another fairness metric ( my choice is normalized discounted difference (rND) )
2. Finishing gender labeling for DBLP
3. adding dblp to the pipeline

**Comment by hosseinfani** [comment]
@Hamedloghmani 
how about equality of odds implementation?

**Comment by Hamedloghmani** [comment]
@hosseinfani 
My understanding from [demographic parity](https://developers.google.com/machine-learning/glossary/fairness#demographic-parity), [equality of opportunity ](https://developers.google.com/machine-learning/glossary/fairness#equality-of-opportunity) and [equalized odds](https://developers.google.com/machine-learning/glossary/fairness#equalized-odds) is that if we want to include equalized odds or equality of opportunity, we have to somehow enter a label to our problem to define whether an expert is 'qualified' or not. And then examine how qualified/non-qualified experts place into the team. I think ( with my knowledge at this point, I might be wrong) these are not suitable for our problem and demographic parity which falls under [group fairness criteria](https://en.wikipedia.org/wiki/Fairness_(machine_learning)#Group_Fairness_criteria) is more helpful.

My personal suggestion is going with Group/Individual fairness criteria instead of the 3 that I mentioned at the beginning since most of the significant work in fairness did the same.

I would be happy to hear your input on this. I can dedicate more time to equalized odds if you believe it would be helpful for us.

**Comment by hosseinfani** [comment]
@Hamedloghmani 
I update the tasks. Please come up with a timeline in this issue page (don't create another doc/issue). 
Also, drop by during office hour every week to discuss your progress.

**Comment by hosseinfani** [comment]
@Hamedloghmani 
pls keep this issue page updated with your fall23 plan.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Sure, the page has been successfully updated with the tasks that we discussed and you kindly mentioned in our Excel sheet.
